CREATE TABLE IF NOT EXISTS `area` (
  `id` int(2) NOT NULL,
  `area` varchar(12) NOT NULL
);

INSERT INTO `area` (`id`, `area`) VALUES (1, '北海道');
INSERT INTO `area` (`id`, `area`) VALUES (2, '青森県');
INSERT INTO `area` (`id`, `area`) VALUES (3, '岩手県');
INSERT INTO `area` (`id`, `area`) VALUES (4, '宮城県');
INSERT INTO `area` (`id`, `area`) VALUES (5, '秋田県');
INSERT INTO `area` (`id`, `area`) VALUES (6, '山形県');
INSERT INTO `area` (`id`, `area`) VALUES (7, '福島県');
INSERT INTO `area` (`id`, `area`) VALUES (8, '茨城県');
INSERT INTO `area` (`id`, `area`) VALUES (9, '栃木県');
INSERT INTO `area` (`id`, `area`) VALUES (10, '群馬県');
INSERT INTO `area` (`id`, `area`) VALUES (11, '埼玉県');
INSERT INTO `area` (`id`, `area`) VALUES (12, '千葉県');
INSERT INTO `area` (`id`, `area`) VALUES (13, '東京都');
INSERT INTO `area` (`id`, `area`) VALUES (14, '神奈川県');
INSERT INTO `area` (`id`, `area`) VALUES (15, '新潟県');
INSERT INTO `area` (`id`, `area`) VALUES (16, '富山県');
INSERT INTO `area` (`id`, `area`) VALUES (17, '石川県');
INSERT INTO `area` (`id`, `area`) VALUES (18, '福井県');
INSERT INTO `area` (`id`, `area`) VALUES (19, '山梨県');
INSERT INTO `area` (`id`, `area`) VALUES (20, '長野県');
INSERT INTO `area` (`id`, `area`) VALUES (21, '岐阜県');
INSERT INTO `area` (`id`, `area`) VALUES (22, '静岡県');
INSERT INTO `area` (`id`, `area`) VALUES (23, '愛知県');
INSERT INTO `area` (`id`, `area`) VALUES (24, '三重県');
INSERT INTO `area` (`id`, `area`) VALUES (25, '滋賀県');
INSERT INTO `area` (`id`, `area`) VALUES (26, '京都府');
INSERT INTO `area` (`id`, `area`) VALUES (27, '大阪府');
INSERT INTO `area` (`id`, `area`) VALUES (28, '兵庫県');
INSERT INTO `area` (`id`, `area`) VALUES (29, '奈良県');
INSERT INTO `area` (`id`, `area`) VALUES (30, '和歌山県');
INSERT INTO `area` (`id`, `area`) VALUES (31, '鳥取県');
INSERT INTO `area` (`id`, `area`) VALUES (32, '島根県');
INSERT INTO `area` (`id`, `area`) VALUES (33, '岡山県');
INSERT INTO `area` (`id`, `area`) VALUES (34, '広島県');
INSERT INTO `area` (`id`, `area`) VALUES (35, '山口県');
INSERT INTO `area` (`id`, `area`) VALUES (36, '徳島県');
INSERT INTO `area` (`id`, `area`) VALUES (37, '香川県');
INSERT INTO `area` (`id`, `area`) VALUES (38, '愛媛県');
INSERT INTO `area` (`id`, `area`) VALUES (39, '高知県');
INSERT INTO `area` (`id`, `area`) VALUES (40, '福岡県');
INSERT INTO `area` (`id`, `area`) VALUES (41, '佐賀県');
INSERT INTO `area` (`id`, `area`) VALUES (42, '長崎県');
INSERT INTO `area` (`id`, `area`) VALUES (43, '熊本県');
INSERT INTO `area` (`id`, `area`) VALUES (44, '大分県');
INSERT INTO `area` (`id`, `area`) VALUES (45, '宮崎県');
INSERT INTO `area` (`id`, `area`) VALUES (46, '鹿児島県');
INSERT INTO `area` (`id`, `area`) VALUES (47, '沖縄県');
