CREATE DATABASE IF NOT EXISTS `phpunit_test`;

CREATE TABLE IF NOT EXISTS `example` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(10),
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
